#!/usr/bin/env python3
"""
Flatten skills/ai-system-architect/SKILL.md and its references/*.md into a
single Markdown file, for use as a system prompt in frameworks that don't
support Claude's progressive-disclosure skill loading (see
docs/USING-WITH-OTHER-AGENTS.md).

Usage:
    python3 tools/build_context_bundle.py [-o OUTPUT_PATH]

Defaults to writing dist/ai-system-architect.full.md relative to the repo
root (i.e. this script's parent directory).
"""

import argparse
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILL_DIR = REPO_ROOT / "skills" / "ai-system-architect"
SKILL_MD = SKILL_DIR / "SKILL.md"
REFERENCES_DIR = SKILL_DIR / "references"

# Order matters a little for readability, though the agent doesn't strictly
# need it in any particular order once bundled.
REFERENCE_ORDER = [
    "evidence-model.md",
    "discovery-playbook.md",
    "analysis-workflows.md",
    "comparison-and-validation.md",
    "adr-and-risk.md",
    "diagrams.md",
    "ai-architecture.md",
    "security-and-safety.md",
    "handoff.md",
    "output-schema.md",
]


def strip_frontmatter(text: str) -> str:
    """Remove the YAML frontmatter block from SKILL.md (name/description are
    Claude-specific triggering metadata, not useful in a flat system prompt).
    """
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            return parts[2].lstrip("\n")
    return text


def rewrite_reference_links(text: str) -> str:
    """Convert `references/foo.md` links/mentions into a pointer to the
    matching section heading in the bundled file, so cross-references still
    make sense once everything lives in one document."""
    def repl(match):
        fname = match.group(1)
        anchor = fname.replace(".md", "").replace("_", "-")
        return f'the "{anchor}" section below'

    return re.sub(r"`references/([a-zA-Z0-9_-]+\.md)`", repl, text)


def build_bundle() -> str:
    if not SKILL_MD.exists():
        raise FileNotFoundError(f"Could not find {SKILL_MD}")

    sections = []
    header = (
        "# AI System Architect — Full Instructions (bundled)\n\n"
        "This is a flattened, single-file version of the AI System "
        "Architect skill, generated for use as a system prompt in "
        "frameworks that don't support Claude's progressive skill loading. "
        "See docs/USING-WITH-OTHER-AGENTS.md in the source repository for "
        "how to use this. Do not edit this file directly — edit "
        "skills/ai-system-architect/SKILL.md and references/*.md, then "
        "regenerate with tools/build_context_bundle.py.\n"
    )
    sections.append(header)

    skill_body = strip_frontmatter(SKILL_MD.read_text(encoding="utf-8"))
    skill_body = rewrite_reference_links(skill_body)
    sections.append(skill_body)

    available = {p.name: p for p in REFERENCES_DIR.glob("*.md")}
    ordered_names = [n for n in REFERENCE_ORDER if n in available] + \
        [n for n in available if n not in REFERENCE_ORDER]

    for name in ordered_names:
        path = available[name]
        title = name.replace(".md", "").replace("-", " ").replace("_", " ").title()
        sections.append(f"\n---\n\n## Reference: {title}\n")
        body = rewrite_reference_links(path.read_text(encoding="utf-8"))
        sections.append(body)

    return "\n".join(sections)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                      formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output",
                         default=str(REPO_ROOT / "dist" / "ai-system-architect.full.md"),
                         help="Output path for the bundled Markdown file")
    args = parser.parse_args()

    bundle = build_bundle()
    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(bundle, encoding="utf-8")
    print(f"Wrote {out_path} ({len(bundle):,} characters)")


if __name__ == "__main__":
    main()
